# Generated by Django 5.1.1 on 2024-10-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'message'},
        ),
    ]
