# Generated by Django 5.1.1 on 2024-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_your_tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('tire_color', models.CharField(max_length=20)),
                ('trim', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'design',
            },
        ),
    ]
